name: Package obs-studio
description: Produces platform-specific archives or images of an OBS Studio build produced on a GitHub Actions runner.
inputs:
  config:
    description: >
      The CMake-style build configuration to use for building OBS Studio.
      Available values are 'Debug', 'RelWithDebInfo', 'Release', and 'MinSizeRel'.
    default: Release
  architecture:
    description: >
      The CPU architecture to build OBS-Studio for.
      Available values are 'arm64' and 'x86_64'.
    required: true
  package:
    description: >
      A boolean value to indicate whether platform-specific packages should be created instead of a compressed archive.
    default: 'false'
  output-name:
    description: A custom output name to use for the generated packages or compressed archives.
    default: ''
  path:
    description: The path that contains the build directory to genreate packages or compressed archives from.
    default: ${{ runner.temp }}
  working-directory:
    description: A path to an OBS Studio checkout.
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Create macOS Package
      if: runner.os == 'macOS'
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        BUILD_CONFIG: ${{ inputs.config }}
        BUILD_TARGET: ${{ inputs.architecture }}
        BUILD_PACKAGE: ${{ inputs.package }}
        OUTPUT_NAME: ${{ inputs.output-name }}
        OUTPUT_PATH: ${{ inputs.path }}
      run: zsh --errexit --pipefail --no-rcs ${GITHUB_ACTION_PATH}/package-macos.zsh

    - name: Create Ubuntu Package
      if: runner.os == 'Linux'
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        BUILD_CONFIG: ${{ inputs.config }}
        BUILD_TARGET: ${{ inputs.architecture }}
        BUILD_PACKAGE: ${{ inputs.package }}
        OUTPUT_NAME: ${{ inputs.output-name }}
        OUTPUT_PATH: ${{ inputs.path }}
      run: ${GITHUB_ACTION_PATH}/package-ubuntu.bash

    - name: Create Windows Package
      if: runner.os == 'Windows'
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        BUILD_CONFIG: ${{ inputs.config }}
        BUILD_TARGET: ${{ case(inputs.architecture == 'x86_64', 'x64', inputs.architecture) }}
        BUILD_PACKAGE: ${{ inputs.package }}
        OUTPUT_NAME: ${{ inputs.output-name }}
        OUTPUT_PATH: ${{ inputs.path }}
      run: ${GITHUB_ACTION_PATH}/package-windows.bash
