# $FreeBSD$

freebsd_instance:
  image: freebsd-13-1-release-amd64

env:
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_CLONE_SUBMODULES: true

task:
  install_script:
  - pkg install -y
    v4l_compat swig ffmpeg curl dbus fdk-aac fontconfig
    freetype2 jackit jansson luajit mbedtls pulseaudio speexdsp
    libpci librist libsysinfo libudev-devd libv4l libx264 cmake ninja
    mesa-libs lua52 pkgconf
    srt
    qt5-svg qt5-qmake qt5-buildtools qt5-x11extras qt5-xml
  script:
  - mkdir build
  - cd build
  - cmake
      -DUNIX_STRUCTURE=1
      -DENABLE_AJA=OFF
      -DENABLE_ALSA=OFF
      -GNinja ..
  - ninja
