target_sources(
  obs-studio
  PRIVATE
    window-basic-about.cpp
    window-basic-about.hpp
    window-basic-adv-audio.cpp
    window-basic-adv-audio.hpp
    window-basic-auto-config-test.cpp
    window-basic-auto-config.cpp
    window-basic-auto-config.hpp
    window-basic-filters.cpp
    window-basic-filters.hpp
    window-basic-interaction.cpp
    window-basic-interaction.hpp
    window-basic-main-browser.cpp
    window-basic-main-dropfiles.cpp
    window-basic-main-icons.cpp
    window-basic-main-outputs.cpp
    window-basic-main-outputs.hpp
    window-basic-main-profiles.cpp
    window-basic-main-scene-collections.cpp
    window-basic-main-screenshot.cpp
    window-basic-main-transitions.cpp
    window-basic-main.cpp
    window-basic-main.hpp
    window-basic-preview.cpp
    window-basic-preview.hpp
    window-basic-properties.cpp
    window-basic-properties.hpp
    window-basic-settings-a11y.cpp
    window-basic-settings-appearance.cpp
    window-basic-settings-stream.cpp
    window-basic-settings.cpp
    window-basic-settings.hpp
    window-basic-source-select.cpp
    window-basic-source-select.hpp
    window-basic-stats.cpp
    window-basic-stats.hpp
    window-basic-status-bar.cpp
    window-basic-status-bar.hpp
    window-basic-transform.cpp
    window-basic-transform.hpp
    window-basic-vcam-config.cpp
    window-basic-vcam-config.hpp
    window-basic-vcam.hpp
    window-dock.cpp
    window-dock.hpp
    window-importer.cpp
    window-importer.hpp
    window-log-reply.cpp
    window-log-reply.hpp
    window-main.hpp
    window-missing-files.cpp
    window-missing-files.hpp
    window-namedialog.cpp
    window-namedialog.hpp
    window-projector.cpp
    window-projector.hpp
    window-remux.cpp
    window-remux.hpp
    window-whats-new.cpp
    window-whats-new.hpp
)
