# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_THREADS "0")
set(CPACK_BUILD_SOURCE_DIRS "/home/subtomic/Documents/GitHub/VRobs-studio;/home/subtomic/Documents/GitHub/VRobs-studio/build_vr")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_DEBUGINFO_PACKAGE "TRUE")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "OBS Project")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "obs-studio built using CMake")
set(CPACK_GENERATOR "DEB")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/subtomic/Documents/GitHub/VRobs-studio/build_vr;obs-studio;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/subtomic/Documents/GitHub/VRobs-studio/cmake/common;/home/subtomic/Documents/GitHub/VRobs-studio/cmake/finders;/home/subtomic/Documents/GitHub/VRobs-studio/cmake/linux")
set(CPACK_NSIS_DISPLAY_NAME "obs-studio 30.0.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "obs-studio 30.0.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/subtomic/Documents/GitHub/VRobs-studio/build_vr/CPackConfig.cmake")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Free and open source software for video recording and live streaming")
set(CPACK_PACKAGE_EXECUTABLES "obs")
set(CPACK_PACKAGE_FILE_NAME "obs-studio-30.0.0-Linux")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://www.obsproject.com")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "obs-studio 30.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "obs-studio 30.0.0")
set(CPACK_PACKAGE_NAME "obs-studio")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "https://www.obsproject.com")
set(CPACK_PACKAGE_VERSION "30.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "30")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/subtomic/Documents/GitHub/VRobs-studio/frontend/data/license/gplv2.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "TRUE")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "/.git;/home/subtomic/Documents/GitHub/VRobs-studio/build_vr;/.ccache;/.deps")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/subtomic/Documents/GitHub/VRobs-studio/build_vr/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "obs-studio-30.0.0-sources")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/subtomic/Documents/GitHub/VRobs-studio/build_vr/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
