# cmake-format: off
# example cross compile
# mkdir build_aarch64
# cd build_aarch64
# cmake -DCMAKE_SYSROOT=your path -DCMAKE_TOOLCHAIN_FILE=../cmake/linux/toolchain-aarch64-gcc.cmake -DENABLE_BROWSER=OFF
# -DENABLE_SCRIPTING=OFF -DENABLE_SCRIPTING_LUA=OFF -DENABLE_SCRIPTING_PYTHON=OFF  -DENABLE_VLC=OFF -DENABLE_BROWSER=OFF
# -DENABLE_WEBSOCKET=OFF=OFF  -DENABLE_AJA=OFF -DENABLE_WEBRTC=OFF -DENABLE_DECKLINK=OFF
# -DENABLE_VST=OFF -DENABLE_QSV11=OFF -G "Ninja"   ..
# cmake-format: on

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm64)

if(CROSS STREQUAL "")
  set(CROSS aarch64-linux-gnu-)
endif()

if(NOT CMAKE_C_COMPILER)
  set(CMAKE_C_COMPILER ${CROSS}gcc)
endif()

if(NOT CMAKE_CXX_COMPILER)
  set(CMAKE_CXX_COMPILER ${CROSS}g++)
endif()

if(NOT CMAKE_ASM_COMPILER)
  set(CMAKE_ASM_COMPILER ${CROSS}as)
endif()
