/*
Copyright (c) 2015-2016, Intel Corporation

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Intel Corporation nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// seg_service.idl : IDL source for seg_service
//

// This file will be processed by the MIDL tool to
// produce the type library (seg_service.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(ADD60B51-95C7-4232-84B0-3CCBBEA7147C),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISegProc : IDispatch{
    HRESULT Init(LPCWSTR bufferName);
    HRESULT Stop();
    HRESULT LockBuffer(int* frame, int* bufferRealloc, int* frameSize);
    HRESULT SetFps(int fps);
    HRESULT GetFps(int* fps);
    HRESULT SetIVCAMMotionRangeTradeOff(int value);
    HRESULT GetIVCAMMotionRangeTradeOff(int* value);
    HRESULT UnlockBuffer();
};
[
	uuid(64BC16FD-9E3C-4904-B9BA-A360310BCFEC),
	version(1.0),
]
library seg_serviceLib
{
	importlib("stdole2.tlb");
	[
		uuid(66917998-CA70-42A6-B8AE-A3A5126123C7)		
	]
	coclass SegProc
	{
		[default] interface ISegProc;
	};
};

