CREATE TABLE "PluginInfo" (
"plug_id"  REAL,
"plug_name"  TEXT,
"img_url"  TEXT,
"file_url"  TEXT,
"file_local_path"  TEXT,
"file_size"  REAL,
"file_md5"  TEXT,
"plug_class"  INTEGER,
"language"  TEXT,
"version"  TEXT,
"_version_"  REAL,
"big_version"  REAL,
"system"  INTEGER,
"system_version"  TEXT,
"plug_status"  INTEGER,
"insert_time"  REAL,
"download_num"  INTEGER,
"recommend"  INTEGER,
"id"  INTEGER,
"order_num"  INTEGER,
"developer"  TEXT,
"synopsis"  TEXT,
"language_info_modifytime"  TEXT,
"info_modifytime"  TEXT
);
