[general]
log_level = "trace"

[env]
# On CI these should be in %PATH%
sevenzip_path = "7z"
makensis_path = "makensis"
pandoc_path = "pandoc"
pdbcopy_path = "C:/Program Files (x86)/Windows Kits/10/Debuggers/x64/pdbcopy.exe"

[prepare.codesign]
skip_sign = true

[generate]
patch_type = "zstd"
compress_files = true

# Prevent some legacy plugins from being marked as deleted
exclude_from_removal = [
    "enc-amf",
    "win-mf",
]

[package]

[package.installer]
skip = true

[package.updater]
vc_redist_path = "bouf/nsis/VC_redist.x64.exe"
skip_sign = true
