find_package(PkgConfig)

pkg_check_modules(PC_LIBSWRESAMPLE QUIET libswresample)
set(LIBSWRESAMPLE_DEFINITIONS ${PC_LIBSWRESAMPLE_CFLAGS_OTHER})

find_path(LIBSWRESAMPLE_INCLUDE_DIR libswresample/swresample.h
	HINTS ${PC_LIBSWRESAMPLE_INCLUDEDIR} ${PC_LIBSWRESAMPLE_INCLUDE_DIRS}
	PATH_SUFFIXES libswresample)

find_library(LIBSWRESAMPLE_LIBRARY NAMES libswresample swresample
	HINTS ${PC_LIBSWRESAMPLE_LIBDIR} ${PC_LIBSWRESAMPLE_LIBRARY_DIRS})

set(LIBSWRESAMPLE_INCLUDE_DIRS ${LIBSWRESAMPLE_INCLUDE_DIR})
set(LIBSWRESAMPLE_LIBRARIES ${LIBSWRESAMPLE_LIBRARY})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(Libswresample DEFAULT_MSG
	LIBSWRESAMPLE_INCLUDE_DIR LIBSWRESAMPLE_LIBRARY)
mark_as_advanced(LIBSWRESAMPLE_INCLUDE_DIR LIBSWRESAMPLE_LIBRARY)
