/* midi notes w/ channel */
#define OBS_HOTKEY_CAT(a,b) OBS_HOTKEY(a##b)
#define OBS_MIDI_KEYS_PARTIAL(n,c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_C ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_CSharp ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_D ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_DSharp ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_E ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_F ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_FSharp ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_G ## n, _CHANNEL ## c)

#define OBS_MIDI_KEYS_FULL(n,c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_C ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_CSharp ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_D ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_DSharp ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_E ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_F ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_FSharp ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_G ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_GSharp ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_A ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_ASharp ## n, _CHANNEL ## c) \
OBS_HOTKEY_CAT(OBS_MIDI_KEY_B ## n, _CHANNEL ## c)

#define OBS_MIDI_KEYS_CHANNEL(n) \
OBS_MIDI_KEYS_FULL(N1, n) \
OBS_MIDI_KEYS_FULL(0, n) \
OBS_MIDI_KEYS_FULL(1, n) \
OBS_MIDI_KEYS_FULL(2, n) \
OBS_MIDI_KEYS_FULL(3, n) \
OBS_MIDI_KEYS_FULL(4, n) \
OBS_MIDI_KEYS_FULL(5, n) \
OBS_MIDI_KEYS_FULL(6, n) \
OBS_MIDI_KEYS_FULL(7, n) \
OBS_MIDI_KEYS_FULL(8, n) \
OBS_MIDI_KEYS_PARTIAL(9, n)

OBS_MIDI_KEYS_CHANNEL(0)
OBS_MIDI_KEYS_CHANNEL(1)
OBS_MIDI_KEYS_CHANNEL(2)
OBS_MIDI_KEYS_CHANNEL(3)
OBS_MIDI_KEYS_CHANNEL(4)
OBS_MIDI_KEYS_CHANNEL(5)
OBS_MIDI_KEYS_CHANNEL(6)
OBS_MIDI_KEYS_CHANNEL(7)
OBS_MIDI_KEYS_CHANNEL(8)
OBS_MIDI_KEYS_CHANNEL(9)
OBS_MIDI_KEYS_CHANNEL(10)
OBS_MIDI_KEYS_CHANNEL(11)
OBS_MIDI_KEYS_CHANNEL(12)
OBS_MIDI_KEYS_CHANNEL(13)
OBS_MIDI_KEYS_CHANNEL(14)
OBS_MIDI_KEYS_CHANNEL(15)

#undef OBS_MIDI_KEYS_CHANNEL
#undef OBS_MIDI_KEYS_FULL
#undef OBS_MIDI_KEYS_PARTIAL

/* midi control codes */
#define OBS_MIDI_CONTROL(a,c) OBS_HOTKEY_CAT(OBS_MIDI_CONTROL##a, _CHANNEL##c)
#define OBS_MIDI_CONTROLS(a, c) \
OBS_MIDI_CONTROL(a##0, c) \
OBS_MIDI_CONTROL(a##1, c) \
OBS_MIDI_CONTROL(a##2, c) \
OBS_MIDI_CONTROL(a##3, c) \
OBS_MIDI_CONTROL(a##4, c) \
OBS_MIDI_CONTROL(a##5, c) \
OBS_MIDI_CONTROL(a##6, c) \
OBS_MIDI_CONTROL(a##7, c) \
OBS_MIDI_CONTROL(a##8, c) \
OBS_MIDI_CONTROL(a##9, c)

#define OBS_MIDI_CONTROLS_CHANNEL(c) \
OBS_MIDI_CONTROLS(, c) \
OBS_MIDI_CONTROLS(1, c) \
OBS_MIDI_CONTROLS(2, c) \
OBS_MIDI_CONTROLS(3, c) \
OBS_MIDI_CONTROLS(4, c) \
OBS_MIDI_CONTROLS(5, c) \
OBS_MIDI_CONTROLS(6, c) \
OBS_MIDI_CONTROLS(7, c) \
OBS_MIDI_CONTROLS(8, c) \
OBS_MIDI_CONTROLS(9, c) \
OBS_MIDI_CONTROLS(10, c) \
OBS_MIDI_CONTROLS(11, c) \
OBS_MIDI_CONTROL(120, c) \
OBS_MIDI_CONTROL(121, c) \
OBS_MIDI_CONTROL(122, c) \
OBS_MIDI_CONTROL(123, c) \
OBS_MIDI_CONTROL(124, c) \
OBS_MIDI_CONTROL(125, c) \
OBS_MIDI_CONTROL(126, c) \
OBS_MIDI_CONTROL(127, c)

OBS_MIDI_CONTROLS_CHANNEL(0)
OBS_MIDI_CONTROLS_CHANNEL(1)
OBS_MIDI_CONTROLS_CHANNEL(2)
OBS_MIDI_CONTROLS_CHANNEL(3)
OBS_MIDI_CONTROLS_CHANNEL(4)
OBS_MIDI_CONTROLS_CHANNEL(5)
OBS_MIDI_CONTROLS_CHANNEL(6)
OBS_MIDI_CONTROLS_CHANNEL(7)
OBS_MIDI_CONTROLS_CHANNEL(8)
OBS_MIDI_CONTROLS_CHANNEL(9)
OBS_MIDI_CONTROLS_CHANNEL(10)
OBS_MIDI_CONTROLS_CHANNEL(11)
OBS_MIDI_CONTROLS_CHANNEL(12)
OBS_MIDI_CONTROLS_CHANNEL(13)
OBS_MIDI_CONTROLS_CHANNEL(14)
OBS_MIDI_CONTROLS_CHANNEL(15)

#undef OBS_MIDI_CONTROLS
#undef OBS_MIDI_CONTROL

#define OBS_MIDI_PROGRAM(n) OBS_HOTKEY(OBS_MIDI_PROGRAM##n)
OBS_MIDI_PROGRAM(0)
OBS_MIDI_PROGRAM(1)
OBS_MIDI_PROGRAM(2)
OBS_MIDI_PROGRAM(3)
OBS_MIDI_PROGRAM(4)
OBS_MIDI_PROGRAM(5)
OBS_MIDI_PROGRAM(6)
OBS_MIDI_PROGRAM(7)
OBS_MIDI_PROGRAM(8)
OBS_MIDI_PROGRAM(9)
OBS_MIDI_PROGRAM(10)
OBS_MIDI_PROGRAM(11)
OBS_MIDI_PROGRAM(12)
OBS_MIDI_PROGRAM(13)
OBS_MIDI_PROGRAM(14)
OBS_MIDI_PROGRAM(15)
#undef OBS_MIDI_PROGRAM

#define OBS_MIDI_PITCH_WHEEL(n) OBS_HOTKEY(OBS_MIDI_PITCH_WHEEL##n)
OBS_MIDI_PITCH_WHEEL(0)
OBS_MIDI_PITCH_WHEEL(1)
OBS_MIDI_PITCH_WHEEL(2)
OBS_MIDI_PITCH_WHEEL(3)
OBS_MIDI_PITCH_WHEEL(4)
OBS_MIDI_PITCH_WHEEL(5)
OBS_MIDI_PITCH_WHEEL(6)
OBS_MIDI_PITCH_WHEEL(7)
OBS_MIDI_PITCH_WHEEL(8)
OBS_MIDI_PITCH_WHEEL(9)
OBS_MIDI_PITCH_WHEEL(10)
OBS_MIDI_PITCH_WHEEL(11)
OBS_MIDI_PITCH_WHEEL(12)
OBS_MIDI_PITCH_WHEEL(13)
OBS_MIDI_PITCH_WHEEL(14)
OBS_MIDI_PITCH_WHEEL(15)
#undef OBS_MIDI_PITCH_WHEEL
