#define OBS_MIDI_KEYS(n) \
OBS_HOTKEY(OBS_MIDI_KEY_C##n) \
OBS_HOTKEY(OBS_MIDI_KEY_CSharp##n) \
OBS_HOTKEY(OBS_MIDI_KEY_D##n) \
OBS_HOTKEY(OBS_MIDI_KEY_DSharp##n) \
OBS_HOTKEY(OBS_MIDI_KEY_E##n) \
OBS_HOTKEY(OBS_MIDI_KEY_F##n) \
OBS_HOTKEY(OBS_MIDI_KEY_FSharp##n) \
OBS_HOTKEY(OBS_MIDI_KEY_G##n) \
OBS_HOTKEY(OBS_MIDI_KEY_GSharp##n) \
OBS_HOTKEY(OBS_MIDI_KEY_A##n) \
OBS_HOTKEY(OBS_MIDI_KEY_ASharp##n) \
OBS_HOTKEY(OBS_MIDI_KEY_B##n)

OBS_MIDI_KEYS(N1)
OBS_MIDI_KEYS(0)
OBS_MIDI_KEYS(1)
OBS_MIDI_KEYS(2)
OBS_MIDI_KEYS(3)
OBS_MIDI_KEYS(4)
OBS_MIDI_KEYS(5)
OBS_MIDI_KEYS(6)
OBS_MIDI_KEYS(7)
OBS_MIDI_KEYS(8)

#define OBS_MIDI_KEYS(n) \
OBS_HOTKEY(OBS_MIDI_KEY_C##n) \
OBS_HOTKEY(OBS_MIDI_KEY_CSharp##n) \
OBS_HOTKEY(OBS_MIDI_KEY_D##n) \
OBS_HOTKEY(OBS_MIDI_KEY_DSharp##n) \
OBS_HOTKEY(OBS_MIDI_KEY_E##n) \
OBS_HOTKEY(OBS_MIDI_KEY_F##n) \
OBS_HOTKEY(OBS_MIDI_KEY_FSharp##n) \
OBS_HOTKEY(OBS_MIDI_KEY_G##n)

OBS_MIDI_KEYS(9)

#undef OBS_MIDI_KEYS

#define OBS_MIDI_CONTROL(n,t) OBS_HOTKEY(OBS_MIDI_CONTROL##n##t)
#define OBS_MIDI_CONTROLS(t) \
OBS_MIDI_CONTROL(t,0) \
OBS_MIDI_CONTROL(t,1) \
OBS_MIDI_CONTROL(t,2) \
OBS_MIDI_CONTROL(t,3) \
OBS_MIDI_CONTROL(t,4) \
OBS_MIDI_CONTROL(t,5) \
OBS_MIDI_CONTROL(t,6) \
OBS_MIDI_CONTROL(t,7) \
OBS_MIDI_CONTROL(t,8) \
OBS_MIDI_CONTROL(t,9) \

OBS_MIDI_CONTROL(0,)
OBS_MIDI_CONTROL(1,)
OBS_MIDI_CONTROL(2,)
OBS_MIDI_CONTROL(3,)
OBS_MIDI_CONTROL(4,)
OBS_MIDI_CONTROL(5,)
OBS_MIDI_CONTROL(6,)
OBS_MIDI_CONTROL(7,)
OBS_MIDI_CONTROL(8,)
OBS_MIDI_CONTROL(9,)

OBS_MIDI_CONTROLS(1)
OBS_MIDI_CONTROLS(2)
OBS_MIDI_CONTROLS(3)
OBS_MIDI_CONTROLS(4)
OBS_MIDI_CONTROLS(5)
OBS_MIDI_CONTROLS(6)
OBS_MIDI_CONTROLS(7)
OBS_MIDI_CONTROLS(8)
OBS_MIDI_CONTROLS(9)
OBS_MIDI_CONTROLS(10)
OBS_MIDI_CONTROLS(11)

OBS_MIDI_CONTROL(120,)
OBS_MIDI_CONTROL(121,)
OBS_MIDI_CONTROL(122,)
OBS_MIDI_CONTROL(123,)
OBS_MIDI_CONTROL(124,)
OBS_MIDI_CONTROL(125,)
OBS_MIDI_CONTROL(126,)
OBS_MIDI_CONTROL(127,)

#undef OBS_MIDI_CONTROLS
#undef OBS_MIDI_CONTROL

#define OBS_MIDI_PROGRAM(n,t) OBS_HOTKEY(OBS_MIDI_PROGRAM##n##t)
#define OBS_MIDI_PROGRAMS(t) \
OBS_MIDI_PROGRAM(t,0) \
OBS_MIDI_PROGRAM(t,1) \
OBS_MIDI_PROGRAM(t,2) \
OBS_MIDI_PROGRAM(t,3) \
OBS_MIDI_PROGRAM(t,4) \
OBS_MIDI_PROGRAM(t,5) \
OBS_MIDI_PROGRAM(t,6) \
OBS_MIDI_PROGRAM(t,7) \
OBS_MIDI_PROGRAM(t,8) \

OBS_MIDI_PROGRAM(0, )
OBS_MIDI_PROGRAM(1, )
OBS_MIDI_PROGRAM(2, )
OBS_MIDI_PROGRAM(3, )
OBS_MIDI_PROGRAM(4, )
OBS_MIDI_PROGRAM(5, )
OBS_MIDI_PROGRAM(6, )
OBS_MIDI_PROGRAM(7, )
OBS_MIDI_PROGRAM(8, )
OBS_MIDI_PROGRAM(9, )

OBS_MIDI_PROGRAMS(1)
OBS_MIDI_PROGRAMS(2)
OBS_MIDI_PROGRAMS(3)
OBS_MIDI_PROGRAMS(4)
OBS_MIDI_PROGRAMS(5)
OBS_MIDI_PROGRAMS(6)
OBS_MIDI_PROGRAMS(7)
OBS_MIDI_PROGRAMS(8)
OBS_MIDI_PROGRAMS(9)
OBS_MIDI_PROGRAMS(10)
OBS_MIDI_PROGRAMS(11)

OBS_MIDI_PROGRAM(120, )
OBS_MIDI_PROGRAM(121, )
OBS_MIDI_PROGRAM(122, )
OBS_MIDI_PROGRAM(123, )
OBS_MIDI_PROGRAM(124, )
OBS_MIDI_PROGRAM(125, )
OBS_MIDI_PROGRAM(126, )
OBS_MIDI_PROGRAM(127, )

#undef OBS_MIDI_PROGRAMS
#undef OBS_MIDI_PROGRAM

#define OBS_MIDI_PITCH_WHEEL(n) OBS_HOTKEY(OBS_MIDI_PITCH_WHEEL##n)
OBS_MIDI_PITCH_WHEEL(0)
OBS_MIDI_PITCH_WHEEL(1)
OBS_MIDI_PITCH_WHEEL(2)
OBS_MIDI_PITCH_WHEEL(3)
OBS_MIDI_PITCH_WHEEL(4)
OBS_MIDI_PITCH_WHEEL(5)
OBS_MIDI_PITCH_WHEEL(6)
OBS_MIDI_PITCH_WHEEL(7)
OBS_MIDI_PITCH_WHEEL(8)
OBS_MIDI_PITCH_WHEEL(9)
OBS_MIDI_PITCH_WHEEL(10)
OBS_MIDI_PITCH_WHEEL(11)
OBS_MIDI_PITCH_WHEEL(12)
OBS_MIDI_PITCH_WHEEL(13)
OBS_MIDI_PITCH_WHEEL(14)
OBS_MIDI_PITCH_WHEEL(15)
