#include <windows.h>
#include <mmdeviceapi.h>
#include <audioclient.h>


#define KSAUDIO_SPEAKER_2POINT1 (KSAUDIO_SPEAKER_STEREO|SPEAKER_LOW_FREQUENCY)
#define KSAUDIO_SPEAKER_SURROUND_AVUTIL (KSAUDIO_SPEAKER_STEREO|\
SPEAKER_FRONT_CENTER)
#define KSAUDIO_SPEAKER_4POINT1 (KSAUDIO_SPEAKER_QUAD|SPEAKER_LOW_FREQUENCY)
#define KSAUDIO_SPEAKER_OCTAGONAL (KSAUDIO_SPEAKER_QUAD|SPEAKER_FRONT_CENTER|\
SPEAKER_SIDE_LEFT|SPEAKER_SIDE_RIGHT|SPEAKER_BACK_CENTER)
#define KSAUDIO_SPEAKER_HEXADECAGONAL (KSAUDIO_SPEAKER_OCTAGONAL|\
SPEAKER_FRONT_LEFT_OF_CENTER|SPEAKER_FRONT_RIGHT_OF_CENTER|\
SPEAKER_TOP_BACK_LEFT|SPEAKER_TOP_BACK_RIGHT| SPEAKER_TOP_BACK_CENTER|\
SPEAKER_TOP_FRONT_LEFT| SPEAKER_TOP_FRONT_RIGHT|SPEAKER_TOP_FRONT_CENTER)

#define safe_release(ptr) \
	do { \
		if (ptr) { \
			ptr->lpVtbl->Release(ptr); \
		} \
	} while (false)
