name: Analyze Project
on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment to use for jobs
        required: true
        type: string
    secrets:
      PVS_LICENSE_NAME:
        description: PVS-Studio license name.
        required: false
      PVS_LICENSE_KEY:
        description: PVS-Studio license key.
        required: false
      RESTREAM_CLIENTID:
        description: OAuth client ID for Restream.io connection.
        required: false
      RESTREAM_HASH:
        description: OAuth client ID hash for Restream.io connection.
        required: false
      TWITCH_CLIENTID:
        description: OAuth client ID for Twitch.tv connection.
        required: false
      TWITCH_HASH:
        description: OAuth client ID hash for Twitch.tv connection.
        required: false
      YOUTUBE_CLIENTID:
        description: OAuth client ID for YouTube.com connection.
        required: false
      YOUTUBE_CLIENTID_HASH:
        description: OAuth client ID hash for YouTube.com connection.
        required: false
      YOUTUBE_SECRET:
        description: OAuth client secret for YouTube.com connection.
        required: false
      YOUTUBE_SECRET_HASH:
        description: OAuth client secret hash for YouTube.com connection.
        required: false
      GPU_PRIORITY_VAL:
        required: false
permissions: {}
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
jobs:
  windows:
    name: Windows (PVS-Studio)
    if: fromJSON(vars.ENABLE_PVS_STUDIO)
    runs-on: windows-2025-vs2026
    environment:
      name: ${{ inputs.environment }}
      deployment: false
    permissions:
      contents: read            # Necessary for repository checkouts.
      security-events: write    # Necessary to post CodeQL security scanning reports
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 1

      - name: Set Up Environment
        id: setup
        run: |
          # Set Up Environment
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          jq -r '.configurePresets[]
            | select(.name == "dependencies")
            | .vendor["obsproject.com/obs-studio"].tools.["pvs-studio"]
            | to_entries
            | map("\(.key)=\(.value|tostring)")
            | .[]' "${PWD}/CMakePresets.json" >> "${GITHUB_OUTPUT}"

      - name: Setup PVS-Studio
        id: pvs-setup
        uses: ./.github/actions/analyze-obs/setup-pvs-studio
        with:
          version: ${{ steps.setup.outputs.version }}
          checksum: ${{ steps.setup.outputs.hash }}
          url: ${{ steps.setup.outputs.baseUrl }}
          user: ${{ secrets.PVS_LICENSE_NAME }}
          license: ${{ secrets.PVS_LICENSE_KEY }}

      - name: Analyze OBS Studio
        id: analyze
        uses: ./.github/actions/analyze-obs/run-pvs-studio
        env:
          RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENT_ID }}
          RESTREAM_HASH: ${{ secrets.RESTREAM_CLIENT_HASH || '0'}}
          TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_HASH: ${{ secrets.TWITCH_CLIENT_HASH || '0' }}
          YOUTUBE_CLIENTID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENTID_HASH: ${{ secrets.YOUTUBE_CLIENT_HASH || '0' }}
          YOUTUBE_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_SECRET_HASH: ${{ secrets.YOUTUBE_CLIENT_SECRET_HASH || '0' }}
          GPU_PRIORITY_VAL: ${{ secrets.GPU_PRIORITY_VAL || '0'}}
        with:
          architecture: x64
          upload-codeql: true

  macos:
    name: macOS (clang-analyze)
    runs-on: macos-26
    environment:
      name: ${{ inputs.environment }}
      deployment: false
    permissions:
      contents: read            # Necessary for repository checkouts.
      security-events: write    # Necessary to post CodeQL security scanning reports
    env:
      XCODE_VERSION: '26.6'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 1

      - name: Analyze OBS Studio
        id: analyze
        uses: ./.github/actions/analyze-obs/run-clang-analyze
        env:
          RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENT_ID }}
          RESTREAM_HASH: ${{ secrets.RESTREAM_CLIENT_HASH || '0' }}
          TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_HASH: ${{ secrets.TWITCH_CLIENT_HASH || '0' }}
          YOUTUBE_CLIENTID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENTID_HASH: ${{ secrets.YOUTUBE_CLIENT_HASH || '0' }}
          YOUTUBE_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_SECRET_HASH: ${{ secrets.YOUTUBE_CLIENT_SECRET_HASH || '0' }}
        with:
          architecture: arm64
          upload-codeql: true
