name: Build Project
on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment to use for jobs
        required: true
        type: string
    secrets:
      RESTREAM_CLIENTID:
        description: OAuth client ID for Restream.io connection.
        required: false
      RESTREAM_HASH:
        description: OAuth client ID hash for Restream.io connection.
        required: false
      TWITCH_CLIENTID:
        description: OAuth client ID for Twitch.tv connection.
        required: false
      TWITCH_HASH:
        description: OAuth client ID hash for Twitch.tv connection.
        required: false
      YOUTUBE_CLIENTID:
        description: OAuth client ID for YouTube.com connection.
        required: false
      YOUTUBE_CLIENTID_HASH:
        description: OAuth client ID hash for YouTube.com connection.
        required: false
      YOUTUBE_SECRET:
        description: OAuth client secret for YouTube.com connection.
        required: false
      YOUTUBE_SECRET_HASH:
        description: OAuth client secret hash for YouTube.com connection.
        required: false
      MACOS_CODE_SIGN_IDENTITY:
        description: Apple Developer identity for macOS code signing.
        required: false
      MACOS_CODE_SIGN_CERT:
        description: Apple Developer certificate for macOS code signing.
        required: false
      MACOS_CODE_SIGN_CERT_PASSWORD:
        description: Apple Developer certificate password for macOS code signing.
        required: false
      MACOS_PROVISIONING_PROFILE:
        description: Apple Developer provisioning profile for macOS code signing.
        required: false
      GPU_PRIORITY_VAL:
        required: false
permissions:
  contents: read                # Necessary for repository checkouts.
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
env:
  GHA_IS_TAG_PUSH: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
  GHA_CHECKOUT_FETCH_DEPTH: ${{ case(github.event_name == 'push' && github.ref_type == 'tag', 1, 0) }}
  GHA_ENABLE_PACKAGING: >-
    ${{ case(
      github.event_name == 'pull_request'
      && contains(github.event.labels.*.name, 'Seeking Testers'), true,
      contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name), true,
      false
    ) }}
  GHA_XCODE_VERSION: '26.6'
jobs:
  build-obs:
    name: OBS Studio
    runs-on: ${{ matrix.runs-on }}
    environment:
      name: ${{ inputs.environment }}
      deployment: false
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-26, ubuntu-26.04, ubuntu-24.04, windows-2025-vs2026]
        architecture: [x86_64, arm64]
        include:
          - runs-on: macos-26
            name: macos
            cache-path: CompilationCache.noindex
          - runs-on: windows-2025-vs2026
            name: windows
          - runs-on: ubuntu-26.04
            name: ubuntu-26.04
            cache-path: .ccache
          - runs-on: ubuntu-24.04
            name: ubuntu-24.04
            cache-path: .ccache
        exclude:
          - runs-on: ubuntu-26.04
            architecture: arm64
          - runs-on: ubuntu-24.04
            architecture: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: ${{ env.GHA_CHECKOUT_FETCH_DEPTH }}

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}

      - name: Generate Short GitHub SHA
        id: short-sha
        uses: ./.github/actions/generate-short-sha

      - name: Restore Compilation Cache
        id: compilation-cache
        if: matrix.name != 'windows'
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ format('{0}/{1}', runner.temp, matrix.cache-path) }}
          key: >-
            ${{ format(
              '{0}-compilation-{1}-{2}',
              matrix.name, matrix.architecture,
              case(
                fromJSON(env.GHA_IS_TAG_PUSH) && fromJSON(steps.semver.outputs.is-valid-semver),
                'Release',
                'RelWithDebInfo'
              )
            ) }}
          restore-keys: |
            ${{ format('{0}-compilation-{1}-', matrix.name, matrix.architecture) }}

      - name: Set Up Code Signing
        id: codesign
        if: matrix.name == 'macos'
        uses: ./.github/actions/codesign-obs/setup-macos
        with:
          identity: ${{ secrets.MACOS_CODE_SIGN_IDENTITY }}
          cert: ${{ secrets.MACOS_CODE_SIGN_CERT }}
          cert-password: ${{ secrets.MACOS_CODE_SIGN_CERT_PASSWORD }}
          provisioning-profile: ${{ secrets.MACOS_PROVISIONING_PROFILE }}

      - name: Build OBS Studio
        id: build
        uses: ./.github/actions/build-obs
        env:
          RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENT_ID }}
          RESTREAM_HASH: ${{ secrets.RESTREAM_CLIENT_HASH || '0' }}
          TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_HASH: ${{ secrets.TWITCH_CLIENT_HASH || '0' }}
          YOUTUBE_CLIENTID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENTID_HASH: ${{ secrets.YOUTUBE_CLIENT_HASH || '0' }}
          YOUTUBE_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_SECRET_HASH: ${{ secrets.YOUTUBE_CLIENT_SECRET_HASH || '0' }}
          GPU_PRIORITY_VAL: ${{ secrets.GPU_PRIORITY_VAL || '0'}}
        with:
          config: >-
            ${{ case(
              fromJSON(env.GHA_IS_TAG_PUSH) && fromJSON(steps.semver.outputs.is-valid-semver),
              'Release',
              'RelWithDebInfo'
            ) }}
          architecture: ${{ matrix.architecture }}
          codesign-ident: ${{ steps.codesign.outputs.identity || '-' }}
          codesign-team: ${{ steps.codesign.outputs.team  || '' }}
          provisioning-profile-id: ${{ steps.codesign.outputs.profile-uuid  || '' }}
          xcode-version: ${{ env.GHA_XCODE_VERSION }}
          xcode-cas-path: ${{ format('{0}/{1}', runner.temp, matrix.cache-path) }}

      - name: Package OBS Studio
        id: package
        if: fromJSON(env.GHA_ENABLE_PACKAGING)
        uses: ./.github/actions/package-obs
        with:
          config: >-
            ${{ case(
              fromJSON(env.GHA_IS_TAG_PUSH)
              && fromJSON(steps.semver.outputs.is-valid-semver), 'Release',
              'RelWithDebInfo'
            ) }}
          architecture: ${{ matrix.architecture }}
          package: ${{ case(github.event_name == 'pull_request', false, true) }}
          output-name: >-
            ${{ format(
              'obs-studio-{0}-{1}-{2}',
              matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}

      - name: Upload Application
        if: fromJSON(env.GHA_ENABLE_PACKAGING)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          path: >-
            ${{ format(
              '{0}/obs-studio-{1}-{2}-{3}{4}.*',
              runner.temp, matrix.name, matrix.architecture, steps.short-sha.outputs.sha,
              case(matrix.name == 'macos' || matrix.name == 'windows', '-unsigned', '')
            ) }}

      - name: Upload Debug Symbols
        if: >-
          matrix.name != 'windows'
          && fromJSON(env.GHA_IS_TAG_PUSH)
          && fromJSON(steps.semver.outputs.is-valid-semver)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          path: >-
            ${{ format(
              '{0}/obs-studio-{1}-{2}-{3}-debug-symbols.*',
              runner.temp, matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}

      - name: Upload Developer Library
        if: >-
          contains(fromJSON('["macos", "windows"]'), matrix.name)
          && fromJSON(env.GHA_IS_TAG_PUSH)
          && fromJSON(steps.semver.outputs.is-valid-semver)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          path: >-
            ${{ format(
              '{0}/obs-studio-{1}-{2}-{3}-plugin-dev.*',
              runner.temp, matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}

      - name: Upload Source Tarball
        if: >-
          matrix.name == 'ubuntu-26.04'
          && fromJSON(env.GHA_IS_TAG_PUSH)
          && fromJSON(steps.semver.outputs.is-valid-semver)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          path: >-
            ${{ format(
              '{0}/obs-studio-{1}-{2}-{3}-sources.tar.gz',
              runner.temp, matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}

      - name: Save Compilation Cache
        if: >-
          ${{
            matrix.name != 'windows'
            && github.event_name != 'pull_request'
            && ! fromJSON(steps.compilation-cache.outputs.cache-hit || 'false')
            && ! fromJSON(steps.semver.outputs.is-valid-semver)
          }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ format('{0}/{1}', runner.temp, matrix.cache-path) }}
          key: >-
            ${{ format(
              '{0}-compilation-{1}-{2}',
              matrix.name, matrix.architecture,
              case(
                github.event_name == 'push'
                && github.ref_type == 'tag'
                && fromJSON(steps.semver.outputs.is-valid-semver), 'Release',
                'RelWithDebInfo'
              )
            ) }}

  flatpak-build:
    name: OBS Studio (Flatpak, x86_64)
    if: ${{ ! (github.event_name == 'push' && github.ref_type == 'tag') }}
    runs-on: ubuntu-26.04
    environment:
      name: ${{ inputs.environment }}
      deployment: false
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08     # zizmor: ignore[unpinned-images]
      options: --privileged
      volumes:
        - /opt/hostedtoolcache/CodeQL:/to_clean/codeql
        - /opt/hostedtoolcache/Python:/to_clean/python
        - /usr/local/.ghcup:/to_clean/ghcup
        - /usr/local/lib/android:/to_clean/android
        - /usr/share/dotnet:/to_clean/dotnet
        - /usr/share/swift:/to_clean/swift
    defaults:
      run:
        shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
    env:
      FLATPAK_BUILD_SHARE_PATH: flatpak_app/files/share
      BUILD_BUNDLE: >-
        ${{ case(
          github.event_name == 'pull_request'
          && contains(github.event.labels.*.name, 'Seeking Testers'), true,
          contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name), true,
          false
        ) }}
    steps:
      - name: Prepare Container Image
        env:
          REMOVE_LIST: 'Android CodeQL GHCup Python Swift dotNET'
        run: |
          # Prepare Container Image
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          declare -a removals
          read -r -a removals <<< "${REMOVE_LIST}"
          for removal in "${removals[@]}"; do
            echo "Removing ${removal} files from runner."
            rm -rf /to_clean/"${removal,,*}"/*
          done

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: ${{ env.GHA_CHECKOUT_FETCH_DEPTH }}

      - name: Add Workspace As Safe Directory
        run: |
          # Add Workspace As Safe Directory
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}

      - name: Create Flatpak Bundle
        uses: ./.github/actions/build-flatpak
        with:
          architecture: x86_64
          bundle: ${{ fromJSON(env.BUILD_BUNDLE) }}
