name: Pull
run-name: ${{ github.event.pull_request.title }} pull request run 🚀
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [master]
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  lint-project:
    name: Format
    uses: ./.github/workflows/lint-project.yaml

  build-project:
    name: Build 🧱
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
    permissions:
      contents: read

  update-documentation:
    name: Update Documentation 📖
    if: github.repository_owner == 'obsproject' && github.base_ref == 'master'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Check for Changed Files ✅
        uses: ./.github/actions/check-changes
        id: checks
        with:
          base: origin/${{ github.base_ref }}
          pathspec: docs/sphinx

      - uses: ./.github/actions/generate-docs
        if: fromJSON(steps.checks.outputs.has-changed-files)
