name: Publish
run-name: Publish Tag - ${{ github.ref_name }}
on:
  release:
    types:
      - published
    branches:
      - master
      - 'release/**'
permissions: {}
concurrency:
  group: ${{ github.workflow }}-publish-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
jobs:
  setup-flathub:
    name: Set Up Flathub Matrix
    if: fromJSON(vars.ENABLE_FLATHUB_PUBLISH)
    runs-on: ubuntu-slim
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      matrix: ${{ steps.check.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}

      - name: Check GitHub Release
        id: check
        env:
          PRE_RELEASE: ${{ steps.semver.outputs.pre-release }}
        run: |
          # Check GitHub Release
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          if [[ -n "${PRE_RELEASE}" ]]; then
            echo 'matrix=["beta"]' >> "${GITHUB_OUTPUT}"
          else
              declare gh_output
              gh_output=$(gh release list --repo "${GITHUB_REPOSITORY}" --exclude-drafts \
                --limit 20 --json 'tagName,isPrerelease')

              declare jq_output
              jq_output="$(jq --raw-output --arg version "${GITHUB_REF_NAME}" '
                (map(select(.isPrerelease == true)) | first | .tagName) as $prerelease_version |
                {
                  "current_index": (map(.tagName == $version) | index(true)),
                  "prerelease_index": (map(.tagName == $prerelease_version) | index(true))
                } | join(" ")
              ' <<< "${gh_output}")"

              {
                declare -i prerelease_index
                declare -i version_index
                read -r version_index prerelease_index <<< "${jq_output}"
                if (( version_index > prerelease_index )); then
                  echo 'matrix=["beta", "stable"]'
                else
                  echo 'matrix=["stable"]'
                fi
              }  >> "${GITHUB_OUTPUT}"
          fi

  publish-to-flathub:
    name: Publish To Flathub
    if: fromJSON(vars.ENABLE_FLATHUB_PUBLISH)
    needs: setup-flathub
    runs-on: ubuntu-26.04
    environment:
      name: code-signing
      deployment: false
    strategy:
      fail-fast: true
      matrix:
        branch: ${{ fromJSON(needs.setup-flathub.outputs.matrix )}}
    env:
      FLATPAK_BUILD_SHARE_PATH: flatpak_app/files/share
      RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENT_ID }}
      RESTREAM_HASH: ${{ secrets.RESTREAM_CLIENT_HASH || '0' }}
      TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
      TWITCH_HASH: ${{ secrets.TWITCH_CLIENT_HASH || '0' }}
      YOUTUBE_CLIENTID: ${{ secrets.YOUTUBE_CLIENT_ID }}
      YOUTUBE_CLIENTID_HASH: ${{ secrets.YOUTUBE_CLIENT_HASH || '0' }}
      YOUTUBE_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
      YOUTUBE_SECRET_HASH: ${{ secrets.YOUTUBE_CLIENT_SECRET_HASH || '0' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08     # zizmor: ignore[unpinned-images]
      options: --privileged
      volumes:
        - /opt/hostedtoolcache/CodeQL:/to_clean/codeql
        - /opt/hostedtoolcache/Python:/to_clean/python
        - /usr/local/.ghcup:/to_clean/ghcup
        - /usr/local/lib/android:/to_clean/android
        - /usr/share/dotnet:/to_clean/dotnet
        - /usr/share/swift:/to_clean/swift
    defaults:
      run:
        shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
    steps:
      - name: Prepare Container Image
        env:
          REMOVE_LIST: 'Android CodeQL GHCup Python Swift dotNET'
        run: |
          # Prepare Container Image
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          declare -a removals
          read -r -a removals <<< "${REMOVE_LIST}"
          for removal in "${removals[@]}"; do
            echo "Removing ${removal} files from runner."
            rm -rf /to_clean/"${removal,,*}"/*
          done

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 0

      - name: Add Workspace As Safe Directory
        run: |
          # Add Workspace As Safe Directory
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}

      - name: Generate Short GitHub SHA
        id: short-sha
        uses: ./.github/actions/generate-short-sha

      - name: Create Flatpak Bundle
        uses: ./.github/actions/build-flatpak
        with:
          architecture: x86_64
          bundle: false

      - name: Publish to Flathub Beta
        uses: flatpak/flatpak-github-actions/flat-manager@401fe28a8384095fc1531b9d320b292f0ee45adb # v6.7
        if: matrix.branch == 'beta'
        with:
          flat-manager-url: https://hub.flathub.org/
          repository: beta
          token: ${{ secrets.FLATHUB_BETA_TOKEN }}
          build-log-url: >-
            ${{ format(
              '{0}/{1}/actions/runs/{2}',
              github.server_url, github.repository, github.run_id
            ) }}

      - name: Publish to Flathub
        uses: flatpak/flatpak-github-actions/flat-manager@401fe28a8384095fc1531b9d320b292f0ee45adb # v6.7
        if: matrix.branch == 'stable'
        with:
          flat-manager-url: https://hub.flathub.org/
          repository: stable
          token: ${{ secrets.FLATHUB_TOKEN }}
          build-log-url: >-
            ${{ format(
              '{0}/{1}/actions/runs/{2}',
              github.server_url, github.repository, github.run_id
            ) }}

  generate-appcasts:
    name: Generate Sparkle AppCast files
    runs-on: macos-26
    if: fromJSON(vars.ENABLE_UPDATE_GENERATION || 'false')
    environment:
      name: code-signing
      deployment: false
    strategy:
      fail-fast: true
      matrix:
        architecture: [arm64, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}
          fail-on-mismatch: true

      - name: Generate Short GitHub SHA
        id: short-sha
        uses: ./.github/actions/generate-short-sha

      - name: Generate Sparkle AppCasts
        uses: ./.github/actions/publish-obs/generate-sparkle-appcast
        with:
          architecture: ${{ matrix.architecture }}
          channel: >-
            ${{ case(
              steps.semver.outputs.pre-release != '', 'beta',
              'stable'
            )}}
          signing-key: ${{ secrets.SPARKLE_PRIVATE_KEY }}
          num-deltas: 3
          rollout-interval: 86400
          custom-title: 'OBS Studio'
          custom-link: 'https://obsproject.com'

  merge-appcasts:
    name: Merge Appcasts
    runs-on: ubuntu-slim
    needs: generate-appcasts
    steps:
      - name: Merge Appcasts
        uses: actions/upload-artifact/merge@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: macos-sparkle-update
          pattern: sparkle-appcast-*
          delete-merged: true

  generate-windows-updates:
    name: Generate Windows Updater Files
    runs-on: windows-2025-vs2026
    if: fromJSON(vars.ENABLE_UPDATE_GENERATION || 'false')
    environment:
      name: code-signing
      deployment: false
    strategy:
      fail-fast: true
      matrix:
        architecture: [arm64, x86_64]
    permissions:
      contents: read            # Necessary to keep workflow base permissions.
      id-token: write           # Necessary to set up Windows code signing credentials.
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}
          fail-on-mismatch: true

      - name: Generate Short GitHub SHA
        id: short-sha
        uses: ./.github/actions/generate-short-sha

      - name: Set Up Google Cloud Credentials
        uses: ./.github/actions/codesign-obs/setup-windows
        with:
          gcp-identity-provider: ${{ secrets.GCP_IDENTITY_POOL }}
          gcp-account-name: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}

      - name: Generate Windows Updater Files
        uses: ./.github/actions/publish-obs/generate-windows-update
        with:
          architecture: ${{ matrix.architecture }}
          channel: >-
            ${{ case(
              steps.semver.outputs.pre-release != '', 'beta',
              'stable'
            ) }}

  publish-to-steam:
    name: Publish To Steam
    if: fromJSON(vars.ENABLE_STEAM_PUBLISH || 'false')
    secrets: inherit            # zizmor: ignore[secrets-inherit]
    permissions:
      contents: read
    uses: ./.github/workflows/publish-steam.yaml
    with:
      environment: code-signing
